version: '3.9'

services:
  bot:
    container_name: bot
    hostname: bot
    build:
      context: ./bot
  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/files/logstash.yml:/app/config/logstash.yml:ro
      - ${PWD}/logstash/files/pipelines.yml:/app/config/pipelines.yml:ro
      - ${PWD}/logstash/files/entrypoints/logstash.sh:/app/entrypoint.sh:ro
      - logstash-data:/app/config/a:ro
  logstash-validator:
    container_name: logstash-validator
    hostname: logstash-validator
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/files/pipelines:/app/config/pipelines:ro
      - ${PWD}/logstash/files/entrypoints/logstash-validator.sh:/app/entrypoint.sh:ro
      - logstash-data:/data:rw

volumes:
  logstash-data: